sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
    secure: E0j3Gd6EyKbiPfcqfeZ17Y0iKpIG7nZ+mXPYD4B+qvx0LtcJBLLl4SJ4aAg5z5lz6+3r6Gi33UJ01z+ozv7CEL+rRFf4BeaVt+Ooo9q+kGEZzTpnPjRkHgrLh15t0ToPmRWuKRCOO/7uUV2B9AlvdydoBEdz/gXMwzdI2eHdT3BVmc1woDFIe3o7ysQPb/azl1x4dak7HHL5x1dmYcu01TgLJFNUSHkXmK0cF12QUa397aaJgSKLUQvpbZa2ZZl2L/YQ3258OsbZw88eiyeG4yfNb5q06Jtgpwq+8UEHKZ8xXTlOHjsP9orjtjdVU6sG+crNMWwScqGDGyNqusmqdQNMgd6mp0+IaD15CZvvY5EDXiruXzkbHXvbmrxqfbH8q2fOr+wMuxtRvX5xZ/kf5XBDkDLnfddkXjW8PWyi5Qs8tY3ugQcPk08GobioG2UrkUnP2tMzCSn2xuTB1JQ5PbhxMpNWslI0If2vfVq0O0imgFLshNC/PcN1mcpPMvk301GBgfIZ3KHnejAEsrUWtZl+53GCH/tExW0a66ZUbkqMqnlP5PDERruDkSatyavPFoVSr4gSxicva2Sh4LSk9i6/OLuMyQ8FWQKxKIrpWhJuJypIX4N9z2vcCmC/irfiR4SdfbGLboebtRU2GabTKro1OVVgSB53Fc6DtJMLXs0=

branches:
  only:
  - master
  - integration

before_install:
- sudo apt-get install pandoc
- gem install asciidoctor
- chmod +x .travis/push.sh
- openssl aes-256-cbc -K $encrypted_764440049a39_key -iv $encrypted_764440049a39_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait 10
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p

after_success:
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DeployOrg
- sfdx force:source:deploy -u DeployOrg -w 10 -p ./force-app
- sfdx force:apex:test:run -u DeployOrg -w 10
- .travis/push.sh

after_failure:
- .travis/push.sh
