sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
    secure: TfMBoTuZ9jx+XRwLltKLbQMbxyNS0lT3ofF9BCJtfud7xT2urR67xelzcu12Dt9CHglkzCwPrb36ytXpIgjdjnntk5mqx0N32eJA8/5g4oXtc+2NVphN1KytYFWK7oypeCm32TlRkZMj0//nQ6YaehR8WdQ8SE5LhOxooinlUeTz/JrWrd7cBFbXWHSx0BF2SvJJzs04BSS+OBCREz2eyKIeclLhoTLwjiPayGZjtRUkyS6gIbf2Cgw0XcVh+8N+zV88afi6cQSDnfEvy7eMtBjnt8CpgpnI0lIh7nVHVQO8ktzrwIVNrXymhqdj/2HOCu0IAnSGSyAUEz+OEHlAKHP4KMUQwFApehzDC/Qth312ZQ/ba3aBolQ0MdbL1mPtT08hUWufR7Ma6fWROREBRoKc16BIUiNhlRPQD5NOHeypx81MtJVpBuHbrh+YrcWSlx/KmrFIVfeoDNMjz689vxtsa54p8LswHiMEXP9I9wQmomqhNuWSPdOBOYhLMlm6HWhn7GfOpbs6I+7QcjBcsEhoAN7I2gMactL409pCG+AFoqaMZ4rGLmSHRRk/Dcpd2sQ2B+MOLGI+qkI28xB+REzu+dILooJBk2Vd/ui48mwjrrp8dgA2b+KXZQ5G/cSw72lRdqCL9l4Owj4CMiEdY6lRbfD4pIL+mbdgcACRTi0=
branches:
  only:
  - master
  - integration

before_install:
- sudo apt-get install pandoc
- gem install asciidoctor
- chmod +x .travis/push.sh
- openssl aes-256-cbc -K $encrypted_764440049a39_key -iv $encrypted_764440049a39_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait 10
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p

after_success:
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DeployOrg
- sfdx force:source:deploy -u DeployOrg -w 10 -p ./force-app
- sfdx force:apex:test:run -u DeployOrg -w 10
- .travis/push.sh

after_failure:
- .travis/push.sh
