sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
branches:
  only:
  - integration
  - master

before_install:
- sudo apt-get install pandoc
- gem install asciidoctor
- chmod +x .travis/push.sh
- chmod +x .travis/revert.sh
- openssl aes-256-cbc -K $encrypted_764440049a39_key -iv $encrypted_764440049a39_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir -p sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait 10 -d 1
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p

after_success:
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DeployOrg
- sfdx force:source:deploy -u DeployOrg -w 10 -p ./force-app
- sfdx force:apex:test:run -u DeployOrg -w 10
- .travis/push.sh
- travis env set LastSuccess test

after_failure:
- .travis/revert.sh
